# Generated by Django 5.1.2 on 2025-12-26 22:56

import apps.accounts.models
from django.db import migrations, models
import uuid


def generate_registration_numbers(apps, schema_editor):
    """Generate registration numbers for existing users"""
    User = apps.get_model('accounts', 'User')
    for user in User.objects.all():
        user.registration_number = "REG" + uuid.uuid4().hex.upper()[:10]
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        # First add the field without unique constraint
        migrations.AddField(
            model_name='user',
            name='registration_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        # Populate registration numbers for existing users
        migrations.RunPython(generate_registration_numbers, reverse_code=migrations.RunPython.noop),
        # Now add the unique constraint and default
        migrations.AlterField(
            model_name='user',
            name='registration_number',
            field=models.CharField(blank=True, default=apps.accounts.models.generate_registration_number, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
